name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          cache: true
          cache-dependency-path: client/go.sum

      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --rm-dist
          workdir: client/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
